### ISSUE TITLE
BigDecimalField parsing

### ISSUE THREAD

**Issue by JeffFaer** [JFXtras/jfxtras-labs#114]
Similar to `LocalDateTextField`, would it be possible to add extra parsing formatters to `BigDecimalField`?

For instance, I want the `BigDecimal` to be displayed as a currency, but I would like the user to be able to input the amount without the currency symbol. The primary `NumberFormat` would be `NumberFormat.getCurrencyInstance()` and one of the secondary `NumberFormat`s would be `NumberFormat.getNumberInstance()`.

**Comment by tbee** [comment]
Not being the author of BigDecimalTextField but of the date textfields, I know it should not be very hard. There is a place in BDTF where the typed string is parsed, and there it should loop over the list of available formatters and see which one successfully parses the string first. The property for the list of formatters can be copied from the date textfields. Could be a nice pull request to contribute Jeffrey :-)

**Comment by JeffFaer** [comment]
It seems like there would be quite a bit of code duplication between `BigDecimalField` and `CalendarTextField`. It might be worthwhile to refactor the code so that the same logic can be used for both. For instance, a non-null property would probably be helpful for `BigDecimalField` as well.

**Comment by tbee** [comment]
Hmmm, an API is not quickly code duplication, so on that non-null property I would not agree. Parsing using a list of formatters, yes. 

OTOH I'm not to big a fan of strongly interlinking two basically distinct controls; if one were to get a new feature, it had to be rolled out on all (assuming more textfields are added in time). This hinders open source development, because changes become too big for free time development. There is a balance to strike there. I've gone down that path with the gauges in labs...

**Comment by tbee** [comment]
closed because of no response
