### ISSUE TITLE
Add BeanPathAdapter support for customized date formating

### ISSUE THREAD

**Issue by ugate** [JFXtras/jfxtras-labs#40]
Currently the BeanPathAdapter uses a SimpleDateFormat of "yyyy-MM-dd'T'HH:mm:ssz" that cannot be configured.

**Comment by TomKrauss** [comment]
Not yet working, as method

``` java
protected static class FieldStringConverter<T> extends StringConverter<T> {
...
public static <VT> VT coerce(final Object v, final Class<VT> targetClass) {
```

references the static DateFormat SDF from class BeanPathAdapter.

thank you for working on this.
Tom

**Comment by tbee** [comment]
Closed because of inactivity

**Comment by vova1987** [comment]
Hi again... ;)
Why close?
I am encountering the same issue...
When trying to bind a java.util.date field of my bean to a DatePicker value property (of type LocalDate)
I get the following exception:
Exception while converting Object to String in bidirectional binding
java.lang.IllegalArgumentException: Unable to set object value: 2015-05-01 on eyeExamDate
    at jfxtras.labs.scene.control.BeanPathAdapter$FieldProperty.set(BeanPathAdapter.java:1816)
The reason is, I believe, the static SDF field of the BeanPathAdapter internal StringConverter class, which is "yyyy-MM-dd'T'HH:mm:ssz" - an is not suitable for date only values, which are printed as yyyy-MM-dd by the java.util.date toString() method.
I also noticed that the previous version of BeanPathAdapter did contain DateFormat property - why was this removed?
Do you have any workaround suggestions in the mean time?

**Comment by tbee** [comment]
As said in the closing comment; the issue has been open for 2 years without any response. You are free to reopen it, but given that it has been stale for so long and the code is in labs, chances are low the developer will be picking this up.
